### ISSUE TITLE
May I know is there any reason why we need to explicitly call "python manage.py makemigrations users"

### ISSUE THREAD

**Issue by yccheok** [wsvincent/djangox#3]
I notice that, for creating custom users as demonstrated in https://www.fomfus.com/articles/how-to-use-email-as-username-for-django-authentication-removing-the-username , calling the following is enough

    python manage.py makemigrations

However, for your djangox example, I notice that we need to explicitly call 

    python manage.py makemigrations users

May I know what is the reason behind this? Thank you.

**Comment by wsvincent** [comment]
Sure! Great question. When you just say `makemigrations` then ALL migrations are run. So if you made database schema changes to the `users` app and also the `blog` app, both are combined into one migrations file. This is a problem down the line for debugging. It's more explicit to specify "which" app you want the migrations file generated for. And it's a good best practice to get into it. That's why we do it :)
