### ISSUE TITLE
Integration with CookieCutter

### ISSUE THREAD

**Issue by voidspacexyz** [wsvincent/djangox#52]
Currently when I am creating a new project, I am expected to clone the repo, and make a lot of manual changes to ensure the apps looks the way I want(Name, logo etc). 

Can this be integrated with cookiecutter (https://cookiecutter.readthedocs.io/en/1.7.2/) to ensure better project creation.

**Comment by wsvincent** [comment]
I understand the question.... yes, it could. The reason I haven't is because I think it adds a lot of complexity I don't feel like dealing with to be honest. My goal is this has a bare minimum configuration to help people get started.

I'm open to being persuaded though. I don't think cookiecutter helps you with name/logo. It might if you don't like the default project name. Or we could have dropdowns for pip/pipenv/docker etc. And later on maybe deployment stuff.

Again, if you can spell it out for me I'm always interested to learn more about what people want. But I also want this to be lightweight. That's the tension.
