### ISSUE TITLE
images folder is missing

### ISSUE THREAD

**Issue by mreguly** [wsvincent/djangox#7]
folder "images" with file "favicon.ico" is missing

**Comment by wsvincent** [comment]
It's there under static/images/favicon.ico. And it's working because if you run the site locally you'll see the image in a web tab. Perhaps you expected the `images` folder to not be within `static`?

Using `static` is a good idea because then we can refer to things in it with the `{% static %}` tag which is what we do in `base.html` template. Also it gives us the option to put ALL static files on a CDN which is a better idea in production than running as part of Django itself.

Let me know if I've misunderstood the issue. Thanks for commenting!
