### ISSUE TITLE
Why not a django maintenance mode

### ISSUE THREAD

**Issue by pythonbrad** [wsvincent/djangox#75]
django-maintenancemode is a middleware that allows you to temporary shutdown your site for maintenance work.
https://github.com/bashu/django-maintenancemode

**Comment by wsvincent** [comment]
Hi @pythonbrad, 
Thanks for the suggestion. That project is new to me but it seems cool. I keep djangox deliberately very simple though I agree that in a more advanced starter kit having a maintenance mode would be a good feature. I'm gonna feature this project next week in Django News though since it is new to me and looks interesting. 
A different approach is https://github.com/fabiocaccamo/django-maintenance-mode if you're familiar with that.
